config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  resources :ratios
  resources :amounts
  resources :currencies do 
  	member do
  		post 'buy', to:'currencies#buy'
  		get 'open_modal', to:'currencies#open_modal'
  		
  	end
  	collection do 
  		get 'get_amounts', to:'currencies#get_amounts'
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get '/signup' => 'users#new'
post '/signup' => 'users#create'

get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'

get '/welcome' => 'welcome#new'
post '/welcome' => 'welcome#create'

get '/currencies' => 'currencies#new'
post '/currencies' => 'currencies#create'

post '/application' => 'application#create'

root to: 'dashboard#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aclabs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">

<div class="row">
       <div class="col-lg-12">
         <nav class="navbar navbar-default">
           <div class="container-fluid">              <div class="navbar-header">
               <%= link_to 'Cryptocurrencies meet Ruby', root_path, class: 'navbar-brand' %>
             </div>              
             <% if current_user %>                
             <ul class="nav navbar-nav">
                 <li><%= link_to 'Currencies', currencies_path %></li>
              </ul>               
               <ul class="nav navbar-nav navbar-right">
                 <li><%= link_to 'Logout', logout_path %></li>
               </ul>
               <p class="navbar-text navbar-right">
                 Welcome, <%= current_user.name %>.
               </p>
             <% else %>
               <ul class="nav navbar-nav">
                <li>
                	
                <fieldset style="float: left">
    

                  <div class="form-group" style="float:left; margin: 10px">
                  <%=label_tag :name%>
                  <%= text_field_tag :name,'', :class=>"form-control"%>
                  </div>

                  <div class="form-group" style="float:left; margin: 10px">
                  <%= label_tag :password %>
                  <%= password_field_tag :password,'', :class=>"form-control" %>
                  </div>


                  <div class="form-group" style="float:left; margin: 10px">
                    <%= submit_tag "Login", :class=> 'btn btn-primary' %>
                
                  </div>
                  </li>
    

                 <li style="float:left ; margin: 10px"><%= link_to 'Sign up', signup_path, class: 'navbar-link' %></li>
               </ul>
             <% end %>            </div><!-- /.container-fluid -->
         </nav>
       </div>
</div>

    <%= yield %>
</div>
  </body>
</html>